language: python
python:
- "3.4"
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
before_script:
- flake8 .
- 'sh -e /etc/init.d/xvfb start'
env:
- DISPLAY=":99.0"
script:
- py.test
