language: python
python:
- "3.4"
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
before_script:
- flake8 .
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- rackup
- sleep 3
script:
- py.test
